# fly.toml app configuration file generated for venta on 2023-10-13T09:56:28-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "venta"
primary_region = "iad"

[build]

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
